Convert braket circuits to qiskit circuits
qiskit-community/qiskit-braket-provider pull request #136
Opened 2024-01-02 16:24 UTC by jcjaskula-aws

### Summary
Implemented a `from_braket` method to convert Braket circuits into Qiskit ones. 

### Details and comments
We keep track of the free parameter names to reuse them if they appear several times in the circuits. Because the dicts  construct parametric gates with a standalone `Parameter`, one needs to extra the class object to recreate a new gate with the right circuit Parameters. 
We add a `measure_all` instruction at the end because Braket measure all qubits.
- [x] non-parametric gates
- [x] parametric gates
- [x] gates with modifiers
- [ ] (deferred to another PR) result types

2024-01-30 16:41 UTC, laurencap requested changes

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +gate_name_to_braket_gate: Dict[str, Callable] = {
globals should be in all caps

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +            instruction = gate_name_to_qiskit_gate.get(operation.lower(), None)
I'm a fan of this

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +    warnings.warn(
Nice

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +def to_braket(circuit: Any) -> Any:
+1 better name

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +            warnings.warn(
+1

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +        circuit = transpile(circuit, basis_gates=translatable_qiskit_gate_names)
I think you should add `optimization_level=0` to this, to avoid making changes before the user requests them (as much as possible)

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +@singledispatch
Why use singledispatch here? Do you have ideas for additional types in this qiskit-braket repo for which `to_braket` would be implemented?

2024-01-30 16:41 UTC, laurencap commented on qiskit_braket_provider/providers/adapter.py
> +        gate_instance = gate_name_to_qiskit_gate.get(gate_name, None)
This work feels like one abstraction layer lower -- so I think there's a good opportunity here to factor out a private function for grabbing `gate_cls, gate_params`.

2024-01-30 16:41 UTC, laurencap commented on tests/providers/test_adapter.py
> +    def test_barrier(self):
Nice

2024-01-30 16:41 UTC, laurencap commented on tests/providers/test_adapter.py
> +        """
Nit: you are mixing formatting patterns for docstrings

2024-01-30 16:41 UTC, laurencap commented on tests/providers/test_adapter.py
>  standard_gates = [
Are these exhaustively tested in the existing tests?

2024-01-30 16:41 UTC, laurencap commented on tests/providers/test_adapter.py
> +        Tests braket to qiskit conversion with standard gates.
Was this meant to be more extensive? It only tests one gate

2024-01-30 16:41 UTC, laurencap commented on tests/providers/test_adapter.py
> +        qiskit_circuit = from_braket(braket_circuit)
Why not `to_qiskit`, or `braket_to_qiskit`? `from_braket` doesn't give any information about the output, which is usually the most important bit. If I see something like `circuit2 = <X>(circuit1)`, I mostly need to know the type of `circuit2` to keep reading

2024-02-01 20:36 UTC, jcjaskula-aws commented on qiskit_braket_provider/providers/adapter.py
> +@singledispatch
Having `QuantumCircuit` and `list[Circuit]` was enough for me to motivate the use of singledispatch. I don't really want to have `to_braket_circuit` and `to_braket_circuits`. We could just remove `to_braket(list[QuantumCircuit])` for now, that's a two-way door. Users can always write the loop themselves or we can add it later.

2024-02-01 20:42 UTC, jcjaskula-aws commented on qiskit_braket_provider/providers/adapter.py
> +@singledispatch
Removing singledispatch for now

2024-02-01 20:44 UTC, jcjaskula-aws commented on tests/providers/test_adapter.py
> +        qiskit_circuit = from_braket(braket_circuit)
changing to `to_qiskit`

2024-02-01 20:44 UTC, jcjaskula-aws commented on tests/providers/test_adapter.py
> +        """
done, thanks.

2024-02-01 20:47 UTC, jcjaskula-aws commented on tests/providers/test_adapter.py
>  standard_gates = [
Yes, see [L161](https://github.com/jcjaskula-aws/qiskit-braket-provider/blob/92d8e90f8e4769e497917456d77250ccb4ba3b22/tests/providers/test_adapter.py). 
However, because we now use the transpiler, these tests are not so relevant as they are more testing the transpiler itself than the translation.

2024-02-01 22:35 UTC, jcjaskula-aws commented on tests/providers/test_adapter.py
> +        Tests braket to qiskit conversion with standard gates.
Yes, I first intended to have something close to how it will be used IRL. I'm adding a more exhaustive test.

2024-02-01 22:37 UTC, jcjaskula-aws commented on qiskit_braket_provider/providers/adapter.py
> +        circuit = transpile(circuit, basis_gates=translatable_qiskit_gate_names)
I would lean towards agreeing but I wonder if it could be seen as a breaking change. Changing for now but I leave this unresolve for more reviews.

2024-02-02 15:43 UTC, laurencap approved these changes
LGTM!

2024-02-03 02:13 UTC, speller26 commented on qiskit_braket_provider/providers/adapter.py
> +TRANSLATABLE_QISKIT_GATE_NAMES = set(GATE_NAME_TO_BRAKET_GATE.keys()).union(
This can be private
```
_TRANSLATABLE_QISKIT_GATE_NAMES
```

2024-02-03 02:13 UTC, speller26 commented on qiskit_braket_provider/providers/adapter.py
> +    qiskit_circuit = QuantumCircuit(max(circuit.qubits) + 1)
If the Braket circuit has non-contiguous qubits, will this function create a Qiskit circuit with more qubits than necessary? Will
```python
circ = Circuit().h(0).cnot(0, 999)
```
create a 1000 qubit circuit?

2024-02-05 04:20 UTC, jcjaskula-aws commented on qiskit_braket_provider/providers/adapter.py
> +    qiskit_circuit = QuantumCircuit(max(circuit.qubits) + 1)
Yes, it was. Qubit registers seem to be only contiguous. 
Created a qubit mapping to map braket qubit registers to range(circuit.qubit_count). I don't think we need to keep the qubit indices so it should be enough.

2024-02-05 04:29 UTC, speller26 approved these changes

2024-02-05 04:32 UTC, merged